parameters:
- name: myArray
  type: string
  default: "[foo: 'FOO', bar: 'BAR']"

variables:
  A: $[join('foo','[aleph, bah]')]
  B: $[upper('bah')]

#"['FOO','BAR']"
steps:
  - script: |
      echo $A
      echo $B