variables:
- name: myJob
  value: MyJob

steps:
- powershell: 
    Write-Host "##[section] This is colored green!"
    Write-Host "##[command] This is colored blue!"
    Write-Host "##[debug] This is colored gray!"
    Write-Host "##[warning] This is a warning!"
    Write-Host "##[error] This is an error!"
