parameters:
- name: myFirstObject
  type: object
  default: default
  values:
   - default
   - ubuntu
   - windows
- name: mySecondObject
  type: object
  default:
    - FOO
    - BAR
    - ZOO

variables:
   A: ${{ join(';',parameters.myFirstObject) }} # outputs default
   B: ${{ join(';',parameters.mySecondObject) }} # outputs nothing

steps:
  - script: |
      echo $A
      echo $B