trigger: 
- master

pool: 
   vmImage: ubuntu-latest

jobs:
- job: myJob
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - bash: echo "Hello world"
  ##[group]Beginning of a group
  ##[warning]Warning message
  ##[error]Error message
  ##[debug]Debug text
  ##[command]Command-line being run
  ##[endgroup]




# variables:
# - name: myJob
#   value: MyJob


# trigger:
# - master

# pool:
#   vmImage: 'ubuntu-latest'

# steps:
# - task: NodeTool@0
#   inputs:
#     versionSpec: '10.x'
#   displayName: 'Install Node.js'

# - script: |
#     printenv
#     npm install
#     npm run build
#   displayName: 'npm install and build'

# - task: CopyFiles@2
#   inputs:
#     Contents: '$(Build.Repository.LocalPath)/**' # Pull the build directory (React)
#     TargetFolder: '$(Build.ArtifactStagingDirectory)'
