parameters:
- name: myArray
  type: string
  default: "[foo: 'FOO', bar: 'BAR']"

variables:
  A: $[join('foo','bah')]
  B: $[upper('bah')]

#"['FOO','BAR']"
steps:
  - script: |
      echo $A
      echo $B