variables:
- name: myJob
  value: MyJob

steps:
- script: echo 'fred'
- powershell: 
    Write-Host "This is a standard log message!"
    Write-Host " --------------------------------- "
    Write-Host "These tags just colorize the logs to improve readability"
    Write-Host "##[section] This is colored green!"
    Write-Host "##[command] This is colored blue!"
    Write-Host "##[debug] This is colored gray!"
    Write-Host " --------------------------------- "
    Write-Host "These tags colorize the logs and are picked up by the build"
    Write-Host "##[warning] This is a warning!"
    Write-Host "##vso[task.logissue type=warning;]This is another warning" 
    Write-Host "##[error] This is an error!"
    Write-Host "##vso[task.logissue type=error;]This is another error"
    Write-Error "Actually fail the build task…"