parameters:
- name: myArray
  type: string
  default: "('FOO','BAR')"

variables:
  A: $[join(';','[foo, bar]')]
  B: $[upper('bah')]
  C: $[join(';', ${{ parameters.myArray }}]

#"['FOO','BAR']"
steps:
  - script: |
      echo $A
      echo $B