# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- none

pool:
  vmImage: 'ubuntu-18.04'
strategy:
  matrix:
    node_8_x:
      node_version: 8.x
    node_9_x:
      node_version: 9.x

steps:
- task: NodeTool@0 
  inputs:
    versionSpec: $(node_version)

- script: npm install

# - script: |
#     npm install
#     npm run build
#   displayName: 'npm install and build'

# - script: |
#     npm pack
#   displayName: 'Package for npm release'

# - task: CopyFiles@2
#   inputs:
#     sourceFolder: '$(Build.SourcesDirectory)'
#     contents: '*.tgz' 
#     targetFolder: $(Build.ArtifactStagingDirectory)/npm
#   displayName: 'Copy npm package'

# - task: CopyFiles@2
#   inputs:
#     sourceFolder: '$(Build.SourcesDirectory)'
#     contents: 'package.json' 
#     targetFolder: $(Build.ArtifactStagingDirectory)/npm
#   displayName: 'Copy package.json'

# - script: |
#     PackageName=$(npm list --json --depth=0 | sed -n 2p | cut -d '"' -f4)
#     NewPackageVersion=$(npm list --json --depth=0 | sed -n 3p | cut -d '"' -f4)
#     PublishedPackageVersion=$(npm show $PackageName version)
#     echo "##vso[task.setvariable variable=NewPackageVersion;]$NewPackageVersion"
#     echo "##vso[task.setvariable variable=PublishedPackageVersion;]$PublishedPackageVersion"
#   displayName: "Extract package versions"

# - task: PublishBuildArtifacts@1
#   inputs:
#     pathtoPublish: '$(Build.ArtifactStagingDirectory)/npm'
#     artifactName: npm
#   displayName: 'Publish npm artifact'


# trigger:
# - none

# pool:
#   vmImage: 'ubuntu-latest'

# steps:
# - task: NodeTool@0
#   inputs:
#     versionSpec: '10.x'
#   displayName: 'Install Node.js'

# - script: |
#     npm install
#     npm run build
#   displayName: 'npm install and build'

# - task: CopyFiles@2
#   inputs:
#     Contents: '**' ## update to match what you want to copy
#     TargetFolder: '$(Build.ArtifactStagingDirectory)'

# - script: echo $(Build.StagingDirectory)
# - powershell: dir

# - task: PublishBuildArtifacts@1
#   inputs: 
#     pathtoPublish: $(Build.ArtifactStagingDirectory) # dist or build files



# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

# trigger:
# - master

# pool:
#   vmImage: 'ubuntu-latest'

# steps:
# - task: NodeTool@0
#   inputs:
#     versionSpec: '10.x'
#   displayName: 'Install Node.js'

# - script: |
#     npm install --only=dev
#     npx mocha
#     npm run build
#   displayName: 'npm install and build'
