parameters:
- name: myArray
  type: string
  default: test
  values:
   - default
   - ubuntu
   - windows

variables:
  A: $[join(';','[foo, bar]')]
  B: $[upper('bah')]
  C: $[join(';', ${{ parameters.myArray }}]

steps:
  - script: |
      echo $A
      echo $B