trigger: 
- master

pool: server

steps:
- task: AzureFunction@1
  inputs:
    function: 'https://myfunctionappgh.azurewebsites.net/api/httptriggercsharp1'
    key: '$(myFunctionKey)'
    method: 'POST'
    queryParameters: 'name=$(checks.StageAttempt)'
    waitForCompletion: 'false'
# - script: |
#           echo "attempt is changing with number of attempts"
#           echo "current attempt is $(system.stageattempt)"
#           echo "current checks is $(checks.stageattempt)"
#           exit 1
# - task: InvokeRESTAPI@1
#   inputs:
#    connectionType: 'connectedServiceNameARM'
#    azureServiceConnection: 'DevOps Pipelines - ARM Horizontal Work (82c135d4-f813-4bec-a93e-60e4323918ee)'
#    method: 'POST'
#    waitForCompletion: 'true'


# stages:
#   - stage: 'first'
#     jobs:
#     - job: 'firststage_job1'
#       steps:
#       - script: |
#               echo "attempt is changing with number of attempts"
#               echo "current attempt is $(system.stageattempt)"
#               echo "current checks is $(checks.stageattempt)"
#               exit 1
#         displayName: 'ischanging-$(system.stageattempt)'     
#         continueOnError: true
#   - stage: 'second'
#     dependsOn: 
#     - first
#     jobs:
#     - deployment: DeployWeb1
#       timeoutInMinutes: 7200
#       displayName: job1
#       environment: 
#         name: ContosoDeploy
#         resourceType: VirtualMachine
#       strategy:
#         runOnce:
#           deploy:
#             steps:
#             - script: |
#                 echo "attempt is changing with number of attempts"
#                 echo "current attempt is $(system.stageattempt)"
#                 echo "current checks attempt is $(checks.stageattempt)"
#                 exit 1
#               displayName: "notchanging-$(system.stageattempt)"
#               continueOnError: true

