variables:
- name: myJob
  value: MyJob

steps:
- script: echo 'fred'
- powershell: 
  ##[group]Beginning of a group
  ##[warning]Warning message	##[warning]Warning message
  ##[error]Error message	##[error]Error message
  ##[section]Start of a section
  ##[debug]Debug-only text	##[debug]Debug-only text
  ##[command]Command-line being run	##[command]Command-line being run
  ##[endgroup]	##[endgroup]
