trigger:
- master

pool: 
    vmImage: 'macOS-latest'

steps:
  - script: echo hello from macOS
  - bash: |
       echo "##vso[task.setvariable variable=sauce]crushed tomatoes"
       echo "##vso[task.setvariable variable=secret.Sauce;issecret=true]crushed tomatoes with garlic"
  - bash: |
       echo "No problem reading $SAUCE"
       echo "But I cannot read $SECRET_SAUCE"