parameters:
  projects:
  - test1
  - test2

variables:
  A: $[join(';','[foo, bar]')]
  B: $[upper('bah')]
  C: $[join(';', ${{ parameters.projects }}]

#"['FOO','BAR']"
steps:
  - script: |
      echo $A
      echo $B