trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: A
  steps:
  - script: exit 1

- job: B
  dependsOn: A
  condition: failed()
  steps:
  - script: echo this will run when A fails

- job: C
  dependsOn:
  - A
  - B
  condition: succeeded('B')
  steps:
  - script: echo this will run when B runs and succeeds


# steps:
# - task: NodeTool@0
#   inputs:
#     versionSpec: '10.x'
#   displayName: 'Install Node.js'

# # - script: |
# #     npm install
# #     npm run build
# #   displayName: 'npm install and build'

# - task: PublishBuildArtifacts@1
#   inputs: 
#     targetPath: '$(Pipeline.Workspace)'
#     artifact: 'drop'
#     publishLocation: 'pipeline'

