parameters:
- name: endpoint
  type: string
  default: ''
- name: rootDirectory
  type: string
  default: $(Pipeline.Workspace)
- name: remoteDirectory
  type: string
  default: '/'
- name: archiveName
  type: string
  default: ''


steps:
  - script: |
      echo ${{ format('endpoint:{0}', parameters.endpoint) }}
