parameters:
- name: myFirstObject
  type: object
  default: default
  values:
   - default
   - ubuntu
   - windows
- name: mySecondObject
  type: object
  default:
    foo: FOO
    bar: BAR

variables:
   A: ${{ join(';',parameters.myFirstObject) }}
   B: ${{ join(';',parameters.mySecondObject) }}

steps:
  - script: |
      echo $A
      echo $B