parameters:
- name: myObject
  type: object
  default:
    foo: FOO
    bar: BAR

variables:
  A: $[join(';','[foo, bar]')]
  B: $[upper('bah')]
  C: $[join(';', ${{ parameters.myObject }}]

#"['FOO','BAR']"
steps:
  - script: |
      echo $A
      echo $B