trigger: 
- master

pool: 
   vmImage: ubuntu-latest

steps:
  - powershell: |
      $OrganizationName = "jukullam"
      Start-Sleep -s 70
      $AzureDevOpsAuthenicationHeader = @{Authorization = 'Basic ' + [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes(":$($PAT)")) }

      $UriOrga = "https://dev.azure.com/$($OrganizationName)/" 
      $uriAccount = $UriOrga + "_apis/projects?api-version=5.1"

      Invoke-RestMethod -Uri $uriAccount -Method get -Headers $AzureDevOpsAuthenicationHeader 
      
      $uriProcess = $UriOrga + "_apis/process/processes?api-version=5.1"
      Invoke-RestMethod -Uri $uriProcess -Method get -Headers $AzureDevOpsAuthenicationHeader



# stages:
#   - stage: 'first'
#     jobs:
#     - job: 'firststage_job1'
#       steps:
#       - script: |
#               echo "attempt is changing with number of attempts"
#               echo "current attempt is $(system.stageattempt)"
#               echo "current checks is $(checks.stageattempt)"
#               exit 1
#         displayName: 'ischanging-$(system.stageattempt)'     
#         continueOnError: true
#   - stage: 'second'
#     dependsOn: 
#     - first
#     jobs:
#     - deployment: DeployWeb1
#       timeoutInMinutes: 7200
#       displayName: job1
#       environment: 
#         name: ContosoDeploy
#         resourceType: VirtualMachine
#       strategy:
#         runOnce:
#           deploy:
#             steps:
#             - script: |
#                 echo "attempt is changing with number of attempts"
#                 echo "current attempt is $(system.stageattempt)"
#                 echo "current checks attempt is $(checks.stageattempt)"
#                 exit 1
#               displayName: "notchanging-$(system.stageattempt)"
#               continueOnError: true

