trigger:
- master

pool: 
    vmImage: 'macOS-latest'

steps:
  - script: echo hello from macOS
  - script: |
       echo "##vso[task.setvariable variable=sauce]crushed tomatoes"
       echo "##vso[task.setvariable variable=secret.Sauce;issecret=t
